name: Nubis Development

permalink: pretty
pygments: true

authors:
  tim:
    full_name: Tim van Dalen
    gplus_id: 100487696573936783003
  walid:
    full_name: Walid Said
    gplus_id: 104993994538898250860
  remco:
    full_name: Remco Plasmeijer
    gplus_id: 102632274470030995679
